# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:31
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='creation time')),
                ('modified',
                 models.DateTimeField(
                     auto_now=True, verbose_name='last modification time')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('verbose_name', models.CharField(max_length=64)),
                ('ordering', models.PositiveSmallIntegerField(default=100)),
                ('term',
                 models.ForeignKey(
                     blank=True,
                     null=True,
                     on_delete=django.db.models.deletion.CASCADE,
                     to='classes.Semester')),
            ],
            options={
                'ordering': ('ordering', 'term', 'verbose_name'),
            },
        ),
        migrations.CreateModel(
            name='StudentVisit',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='creation time')),
                ('modified',
                 models.DateTimeField(
                     auto_now=True, verbose_name='last modification time')),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('reason',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='student_visit.Reason')),
                ('sections',
                 models.ManyToManyField(blank=True, to='classes.Section')),
                ('student',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='students.Student')),
            ],
            options={
                'ordering': ('when', ),
            },
        ),
    ]
