# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 13:40
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False,
                max_length=64,
                populate_from='verbose_name',
                unique=True),
        ),
    ]
